version: '3'
services:
  web-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=P@ssword123
      - DB_NAME=akcommodities
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssword123
      - MYSQL_DATABASE=akcommodities
    ports:
      - "3306:3306"
